alter table TELEGRAMSHOP_SEND_FOTO add constraint FK_TELEGRAMSHOP_SEND_FOTO_ON_FILE foreign key (FILE_ID) references SYS_FILE(ID);
alter table TELEGRAMSHOP_SEND_FOTO add constraint FK_TELEGRAMSHOP_SEND_FOTO_ON_USER_MSG foreign key (USER_MSG_ID) references TELEGRAMSHOP_USER(ID);
create index IDX_TELEGRAMSHOP_SEND_FOTO_ON_FILE on TELEGRAMSHOP_SEND_FOTO (FILE_ID);
create index IDX_TELEGRAMSHOP_SEND_FOTO_ON_USER_MSG on TELEGRAMSHOP_SEND_FOTO (USER_MSG_ID);
