alter table TELEGRAMSHOP_FOODS add constraint FK_TELEGRAMSHOP_FOODS_ON_FILE foreign key (FILE_ID) references SYS_FILE(ID);
create index IDX_TELEGRAMSHOP_FOODS_ON_FILE on TELEGRAMSHOP_FOODS (FILE_ID);
